<?php
// $Id$

/**
 * @file
 * The Search Lucene API module's implementation of the the Facet API.
 */

/**
 * Implementation of hook_menu().
 */
function facetapi_luceneapi_menu() {
  $items = array();

  // Iterates over all searchable modules, adds menu items.
  foreach (luceneapi_searchable_module_list() as $searcher => $name) {
    $items['admin/settings/'. $searcher .'/facetapi'] = array(
      'title' => 'Facets',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('facetapi_admin_settings_form', $searcher),
      'access arguments' => array('administer search'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'facetapi.admin.inc',
      'file path' => drupal_get_path('module', 'facetapi'),
      'weight' => 10,
    );
  }

  return $items;
}

/**
 * Implementation of hook_facetapi_adapters().
 */
function facetapi_luceneapi_facetapi_adapters() {
  $adapters = array();

  // Iterates over searchable Search Lucene API modules, builds adapter information.
  foreach (luceneapi_searchable_module_list() as $searcher => $name) {
    $adapters[$searcher] = array(
      'class' => 'FacetapiLuceneapiAdapter',
      'type' => luceneapi_index_type_get($searcher),
      'file' => '/facetapi_luceneapi.adapter.inc',
    );
  }

  return $adapters;
}

/**
 * Implementation of hook_facetapi_facets_alter().
 */
function facetapi_luceneapi_facetapi_facets_alter(&$facets, $searcher, $type) {
  // Adds "delimiter" directive to facets.

}

/**
 * Implementation of hook_facetapi_postrender_alter().
 */
function facetapi_facetapi_postrender_alter(&$rendered, $searcher, $type, $realm_name) {
  if ('luceneapi_node' == $searcher && isset($rendered['created'])) {
    $items = &$rendered['created']['items'];

    // Gets values, finds minimum and maximum.
    $values = array_keys($items);
    $gap = facetapi_timestamp_gap_get(min($values), max($values));
    foreach ($values as $value) {
      $items[$value]['text'] = facetapi_timestamp_format($value, $gap);
    }

  }
}


/**
 * Implementation of hook_luceneapi_query_alter().
 */

