<?php

/**
 * @file
 *
 */

/**
 * Implements hook_facetapi_searcher_info().
 */
function facetapi_apachesolr_facetapi_searcher_info() {
  return array(
    'apachesolr_search' => array(
      'label' => t('Apachesolr'),
      'adapter' => 'apachesolr',
      'instance' => 'apachesolr',
      'path' => 'admin/config/search/apachesolr',
    ),
  );
}

/**
 * Implements hook_facetapi_adapters().
 */
function facetapi_apachesolr_facetapi_adapters() {
  return array(
    'apachesolr' => array(
      'handler' => array(
        'class' => 'FacetapiApachesolrFacetapiAdapter',
      ),
    ),
  );
}

/**
 * Implements hook_facetapi_query_types().
 */
function facetapi_apachesolr_facetapi_query_types() {
  return array(
    'apachesolr_term' => array(
      'handler' => array(
        'class' => 'FacetapiApachesolrTerm',
        'adapter' => 'apachesolr',
      ),
    ),
    'apachesolr_date' => array(
      'handler' => array(
        'class' => 'FacetapiApachesolrDate',
        'adapter' => 'apachesolr',
      ),
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function facetapi_apachesolr_menu_alter(&$items) {
  //$items['admin/config/search/apachesolr/enabled-filters']['access callback'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds breadcrumb trail for Apache Solr administrative pages.
 *
 * @todo Make this a method hook.
 */
function facetapi_apachesolr_form_facetapi_ui_facet_settings_form_alter(&$form, &$form_state) {
  /*
  $module = $form['realm']['sort']['table']['#facetapi']['adapter']->getModule();
  if ('facetapi_apachesolr' == $module) {

    // Initializes breadcrumb.
    $breadcrumb = drupal_get_breadcrumb();
    $breadcrumb[] = l(t('Administration'), 'admin');
    $breadcrumb[] = l(t('Configuration'), 'admin/config');
    $breadcrumb[] = l(t('Search and metadata'), 'admin/config/search');
    $breadcrumb[] = l(t('Apache Solr'), 'admin/config/search/apachesolr');
    $breadcrumb[] = l(t('Facets'), 'admin/config/search/apachesolr/facets');

    // Adds realm to breadcrumb.
    $realm = $form['realm']['sort']['table']['#facetapi']['realm'];
    $breadcrumb[] = l($realm['label'], 'admin/config/search/apachesolr/facets/' . $realm['name']);

    drupal_set_breadcrumb($breadcrumb);
  }
  */
}

/**
 * Implements hook_apachesolr_prepare_query().
 *
 * Adds facet filters to query using "query_types" plugins.
 */
function facetapi_apachesolr_apachesolr_prepare_query($query, $caller) {
  facetapi_add_facets($caller, $query);

  /*
  facetapi_query_type_hooks_invoke('apachesolr_search', $query);

  // Gets enabled facets, adds filter queries to $params.
  $adapter = facetapi_adapter_load('apachesolr_search');
  foreach (facetapi_enabled_facets_get('apachesolr_search') as $facet) {
    $queries = array();
    foreach ($adapter->getActiveItems($facet) as $value => $item) {
      $queries[] = $facet['field alias'] . ':' . $value;
    }
    if (!empty($queries)) {
      $query->params['fq'][$facet['field alias']] = $queries;
    }
  }
  */
}

