<?php

/**
 * @file
 *
 */

/**
 * Implements hook_menu().
 */
function facetapi_ui_menu() {
  $items = array();

  // Builds the realm settings forms for each searcher.
  foreach (facetapi_get_adapter_info() as $searcher => $adapter_info) {

    $first = TRUE;
    foreach (facetapi_get_realm_info() as $realm_name => $realm) {
      if ($first) {
        $first = FALSE;

        $items[$adapter_info['path'] . '/facets'] = array(
          'title' => 'Facets',
          'page callback' => 'drupal_get_form',
          'page arguments' => array('facetapi_ui_realm_settings_form', 'apachesolr_search', $realm_name),
          'access arguments' => array('administer search'),
          'type' => MENU_LOCAL_TASK,
          'file' => 'facetapi_ui.admin.inc',
        );

        $items[$adapter_info['path'] . '/facets/' . $realm_name] = array(
          'title' => $realm['label'],
          'type' => MENU_DEFAULT_LOCAL_TASK,
          'weight' => $realm['weight'],
        );

      }
      else {

        $items[$adapter_info['path'] . '/facets/' . $realm_name] = array(
          'title' => $realm['label'],
          'page callback' => 'drupal_get_form',
          'page arguments' => array('facetapi_ui_realm_settings_form', 'apachesolr_search', $realm_name),
          'access arguments' => array('administer search'),
          'type' => MENU_LOCAL_TASK,
          'file' => 'facetapi_ui.admin.inc',
        );
      }
    }

  }

  $items['admin/config/search/facetapi/%facetapi_adapter/%facetapi_realm/%facetapi_facet/edit'] = array(
    'title' => 'Edit facet configuration',
    'load arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('facetapi_ui_facet_settings_form', 4, 5, 6),
    'access arguments' => array('administer search'),
    'type' => MENU_CALLBACK,
     'file' => 'facetapi_ui.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function facetapi_ui_theme() {
  return array(
    'facetapi_ui_realm_settings_table' => array(
      'render element' => 'element',
      'file' => 'facetapi_ui.admin.inc',
    ),
    'facetapi_ui_sort_settings_table' => array(
      'render element' => 'element',
      'file' => 'facetapi_ui.admin.inc',
    ),
  );
}
