<?php
// $Id$

/**
 * @file
 * The core Search module's implementation of the the Facet API.
 */

/**
 * Implementation of hook_facetapi_adapters().
 */
function facetapi_search_facetapi_adapters() {
  return array(
    'search' => array(
      'class' => 'FacetapiSearchAdapter',
      'arguments' => array('search', 'node'),
      'file' => drupal_get_path('module', 'facetapi_search') .'/facetapi_search.adapter.inc',
    ),
  );
}
